name: seal-build

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '0.10'
      - run: npm run build
      - run: npm i -g npm@1.2.25
      - run: npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: jquery-1.11.1
          path: jquery-1.11.1.tgz
          if-no-files-found: error
